ciração das classes de testes para o pacote handler e service

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -18,7 +18,7 @@ jobs:
   # JOB 1: TEST
   # ------------------------------------------------------------------
   test:
-    name: Unit Tests
+    name: Unit Tests & Coverage
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
@@ -27,11 +27,30 @@ jobs:
       - name: Setup Go
         uses: actions/setup-go@v4
         with:
-          go-version: '1.21'
+          go-version: '1.24'
           cache: true
 
-      - name: Run Tests
-        run: go test -v ./...
+      - name: Run Tests with Coverage
+        id: test-coverage
+        run: |
+          echo "Running Tests..."
+          
+          # 1. Rodamos testes APENAS nos pacotes de lógica (Service e Handler)
+          # Ignoramos: cmd, config, domain, mocks, repository, api
+          go test -v -coverprofile=coverage.out ./internal/service/... ./internal/handler/...
+          
+          # 2. Extrai a porcentagem total do arquivo de cobertura
+          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | tr -d '%')
+          
+          echo "Current Coverage: $COVERAGE%"
+          
+          # 3. Verifica se é menor que 80.0 usando awk (bc nem sempre tem no runner)
+          if awk "BEGIN {exit !($COVERAGE < 80.0)}"; then
+            echo "FAILED: Code coverage is below 80% ($COVERAGE%)"
+            exit 1
+          else
+            echo "PASSED: Code coverage is above 80%"
+          fi
 
   # ------------------------------------------------------------------
   # JOB 2: BUILD & PUSH
